"""empty message

Revision ID: fce392033a88
Revises: 143fc7b51e5c
Create Date: 2018-10-25 13:24:55.752561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce392033a88'
down_revision = '143fc7b51e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_recipe_association',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.add_column(u'ingredient', sa.Column('unit', sa.String(), nullable=True))
    op.add_column(u'recipe', sa.Column('initial_portions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'recipe', 'initial_portions')
    op.drop_column(u'ingredient', 'unit')
    op.drop_table('ingredient_recipe_association')
    # ### end Alembic commands ###
